name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  linux-native:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=MinSizeRel 

    - name: Build
      run: cmake --build build/ 


  linux-emscripten:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Emscripten Install
        run: ./scripts/emscripten-install.sh || true

      - name: Emscripten Build
        run: ./scripts/emscripten-build.sh

  windows-native:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Configure CMake
        shell: cmd
        run: cmake -H. -Bbuild -G "Visual Studio 16 2019" -T ClangCL -DCMAKE_BUILD_TYPE=MinSizeRel

      - name: Build
        shell: cmd
        run: cmake --build build --config MinSizeRel
