name: CodeCov

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux-native:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3