name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  linux-native:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=MinSizeRel 

    - name: Build
      run: cmake --build build/
